name: CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: npm install, test and lint
        run: |
          npm install --frozen-lockfile
          npm run type-check
          npm run eslint:fix
          npm run stylelint:fix
          npm run format
      - name: Count changes
        id: changes
        run: |
          git add -N .
          echo "count=$(git diff --name-only | wc -l)" >> $GITHUB_OUTPUT
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "fix format"
          git push
        if: steps.changes.outputs.count > 0

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
